import 'dart:async';

import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../core/auth/auth_provider.dart';
import '../../core/i18n/language_provider.dart';
import '../../shared/models/quote.dart';
import '../home/providers/quotes_provider.dart';
import '../onboarding/providers/onboarding_provider.dart';
import '../preferences/providers/content_topics_provider.dart';
import 'affirmation_api.dart';
import 'affirmation_context.dart';

// Model `topic` → an existing feed category id (so filtering, muted content and
// the category eyebrow keep working). Anything unknown falls back to motivation.
const _topicToCategory = {
  'confidence': 'confidence',
  'self_worth': 'confidence',
  'self_image': 'confidence',
  'self_esteem': 'confidence',
  'women': 'women',
  'motivation': 'motivation',
  'inspiration': 'motivation',
  'discipline': 'motivation',
  'hard_times': 'healing',
  'letting_go': 'healing',
  'positivity': 'happiness',
  'focus': 'productivity',
  'productivity': 'productivity',
  'success': 'success',
  'money': 'business',
  'business': 'business',
  'love': 'love',
  'relationships': 'love',
  'healing': 'healing',
  'calm': 'stress',
  'stress': 'stress',
  'anxiety': 'stress',
  'mindfulness': 'mindfulness',
  'gratitude': 'gratitude',
  'happiness': 'happiness',
  'health': 'happiness',
  'family': 'family',
  'life': 'life',
  'philosophy': 'philosophy',
  'sport': 'sports',
  'sports': 'sports',
  'workout': 'workout',
  'faith': 'faith',
};

String _categoryFor(String topic) {
  final key = topic.toLowerCase().replaceAll(RegExp(r'[\s-]'), '_');
  return _topicToCategory[key] ?? 'motivation';
}

/// Personalized affirmations for today, generated by the backend from the
/// user's preferences. Loads once when the user signs in (cleared on sign-out).
/// While empty (loading / signed out / offline) the feed keeps using the seed
/// catalog, so the screen is never blank — see [allQuotesProvider].
class DailyAffirmationsNotifier extends StateNotifier<List<Quote>> {
  DailyAffirmationsNotifier(this._ref) : super(const []) {
    _ref.listen<bool>(
      isSignedInProvider,
      (_, signedIn) => signedIn ? _load() : state = const [],
      fireImmediately: true,
    );
    // Regenerate when the user changes what drives the affirmations. The
    // backend only re-calls the model if the preference signature actually
    // changed, so unrelated edits are cheap. Debounced to batch rapid edits.
    _ref.listen(onboardingProvider, (_, _) => _scheduleReload());
    _ref.listen(languageProvider, (_, _) => _scheduleReload());
    _ref.listen(selectedCategoriesProvider, (_, _) => _scheduleReload());
    _ref.listen(contentTopicsProvider, (_, _) => _scheduleReload());
  }

  final Ref _ref;
  bool _loading = false;
  Timer? _debounce;

  Future<void> refresh() => _load();

  void _scheduleReload() {
    if (!_ref.read(isSignedInProvider)) return;
    _debounce?.cancel();
    _debounce = Timer(const Duration(milliseconds: 800), _load);
  }

  @override
  void dispose() {
    _debounce?.cancel();
    super.dispose();
  }

  Future<void> _load() async {
    if (_loading) return;
    _loading = true;
    try {
      // The topics picked in Content preferences are the primary subjects,
      // plus any active Mix selection.
      final context = buildAffirmationContext(
        answers: _ref.read(onboardingProvider),
        language: _ref.read(languageProvider).code,
        extraTopics: [
          ..._ref.read(contentTopicsProvider),
          ..._ref.read(selectedCategoriesProvider),
        ],
      );
      final localDate = _todayLocal();
      final list = await _ref
          .read(affirmationApiProvider)
          .fetchDaily(context: context, localDate: localDate);
      state = [
        for (var i = 0; i < list.length; i++)
          Quote(
            id: 'ai-$localDate-$i',
            text: list[i].text,
            author: '',
            categoryId: _categoryFor(list[i].topic),
          ),
      ];
    } catch (_) {
      // Any failure → leave empty; the feed falls back to the seed catalog.
      state = const [];
    } finally {
      _loading = false;
    }
  }

  String _todayLocal() {
    final n = DateTime.now();
    final m = n.month.toString().padLeft(2, '0');
    final d = n.day.toString().padLeft(2, '0');
    return '${n.year}-$m-$d';
  }
}

final dailyAffirmationsProvider =
    StateNotifierProvider<DailyAffirmationsNotifier, List<Quote>>(
  (ref) => DailyAffirmationsNotifier(ref),
);
